#region

using System;
using System.Collections;

#endregion

namespace HitopsCommon
{
    class CrystalReportField
    {
        private String value1 = "";
        private String value2 = "";
        private String value3 = "";
        private String value4 = "";
        private String value5 = "";
        private String value6 = "";
        private String value7 = "";
        private String value8 = "";
        private String value9 = "";
        private String value10 = "";
        private String value11 = "";
        private String value12 = "";
        private String value13 = "";
        private String value14 = "";
        private String value15 = "";
        private String value16 = "";
        private String value17 = "";
        private String value18 = "";
        private String value19 = "";
        private String value20 = "";
        private String value21 = "";
        private String value22 = "";
        private String value23 = "";
        private String value24 = "";
        private String value25 = "";
        private String value26 = "";
        private String value27 = "";
        private String value28 = "";
        private String value29 = "";
        private String value30 = "";
        private String value31 = "";
        private String value32 = "";
        private String value33 = "";
        private String value34 = "";
        private String value35 = "";
        private String value36 = "";
        private String value37 = "";
        private String value38 = "";
        private String value39 = "";
        private String value40 = "";
        private String value41 = "";
        private String value42 = "";
        private String value43 = "";
        private String value44 = "";
        private String value45 = "";
        private String value46 = "";
        private String value47 = "";
        private String value48 = "";
        private String value49 = "";
        private String value50 = "";
        private String value51 = "";
        private String value52 = "";
        private String value53 = "";
        private String value54 = "";
        private String value55 = "";
        private String value56 = "";
        private String value57 = "";
        private String value58 = "";
        private String value59 = "";
        private String value60 = "";
        private String value61 = "";
        private String value62 = "";
        private String value63 = "";
        private String value64 = "";
        private String value65 = "";
        private String value66 = "";
        private String value67 = "";
        private String value68 = "";
        private String value69 = "";
        private String value70 = "";
        private String value71 = "";
        private String value72 = "";
        private String value73 = "";
        private String value74 = "";
        private String value75 = "";
        private String value76 = "";
        private String value77 = "";
        private String value78 = "";
        private String value79 = "";
        private String value80 = "";
        private String value81 = "";
        private String value82 = "";
        private String value83 = "";
        private String value84 = "";
        private String value85 = "";
        private String value86 = "";
        private String value87 = "";
        private String value88 = "";
        private String value89 = "";
        private String value90 = "";
        private String value91 = "";
        private String value92 = "";
        private String value93 = "";
        private String value94 = "";
        private String value95 = "";
        private String value96 = "";
        private String value97 = "";
        private String value98 = "";
        private String value99 = "";
        private String value100= "";

        //private int ivalue1 = "";
        //private int ivalue2 = "";
        //private int ivalue3 = "";
        //private int ivalue4 = "";
        //private int ivalue5 = "";
        //private int ivalue6 = "";
        //private int ivalue7 = "";
        //private int ivalue8 = "";
        //private int ivalue9 = "";
        //private int ivalue10 = "";
        //private int ivalue11 = "";
        //private int ivalue12 = "";
        //private int ivalue13 = "";
        //private int ivalue14 = "";
        //private int ivalue15 = "";
        //private int ivalue16 = "";
        //private int ivalue17 = "";
        //private int ivalue18 = "";
        //private int ivalue19 = "";
        //private int ivalue20 = "";
        //private int ivalue21 = "";
        //private int ivalue22 = "";
        //private int ivalue23 = "";
        //private int ivalue24 = "";
        //private int ivalue25 = "";
        //private int ivalue26 = "";
        //private int ivalue27 = "";
        //private int ivalue28 = "";
        //private int ivalue29 = "";
        //private int ivalue30 = "";
        //private int ivalue31 = "";
        //private int ivalue32 = "";
        //private int ivalue33 = "";
        //private int ivalue34 = "";
        //private int ivalue35 = "";
        //private int ivalue36 = "";
        //private int ivalue37 = "";
        //private int ivalue38 = "";
        //private int ivalue39 = "";
        //private int ivalue40 = "";
        //private int ivalue41 = "";
        //private int ivalue42 = "";
        //private int ivalue43 = "";
        //private int ivalue44 = "";
        //private int ivalue45 = "";
        //private int ivalue46 = "";
        //private int ivalue47 = "";
        //private int ivalue48 = "";
        //private int ivalue49 = "";
        //private int ivalue50 = "";
        //private int ivalue51 = "";
        //private int ivalue52 = "";
        //private int ivalue53 = "";
        //private int ivalue54 = "";
        //private int ivalue55 = "";
        //private int ivalue56 = "";
        //private int ivalue57 = "";
        //private int ivalue58 = "";
        //private int ivalue59 = "";
        //private int ivalue60 = "";
        //private int ivalue61 = "";
        //private int ivalue62 = "";
        //private int ivalue63 = "";
        //private int ivalue64 = "";
        //private int ivalue65 = "";
        //private int ivalue66 = "";
        //private int ivalue67 = "";
        //private int ivalue68 = "";
        //private int ivalue69 = "";
        //private int ivalue70 = "";
        //private int ivalue71 = "";
        //private int ivalue72 = "";
        //private int ivalue73 = "";
        //private int ivalue74 = "";
        //private int ivalue75 = "";
        //private int ivalue76 = "";
        //private int ivalue77 = "";
        //private int ivalue78 = "";
        //private int ivalue79 = "";
        //private int ivalue70 = "";
        //private int ivalue81 = "";
        //private int ivalue82 = "";
        //private int ivalue83 = "";
        //private int ivalue84 = "";
        //private int ivalue85 = "";
        //private int ivalue86 = "";
        //private int ivalue87 = "";
        //private int ivalue88 = "";
        //private int ivalue89 = "";
        //private int ivalue90 = "";
        //private int ivalue91 = "";
        //private int ivalue92 = "";
        //private int ivalue93 = "";
        //private int ivalue94 = "";
        //private int ivalue95 = "";
        //private int ivalue96 = "";
        //private int ivalue97 = "";
        //private int ivalue98 = "";
        //private int ivalue99 = "";
        //private int ivalue100 = "";

        public String VALUE1 { get { return value1; } set { value1 = value; } }
        public String VALUE2 { get { return value2; } set { value2 = value; } }
        public String VALUE3 { get { return value3; } set { value3 = value; } }
        public String VALUE4 { get { return value4; } set { value4 = value; } }
        public String VALUE5 { get { return value5; } set { value5 = value; } }
        public String VALUE6 { get { return value6; } set { value6 = value; } }
        public String VALUE7 { get { return value7; } set { value7 = value; } }
        public String VALUE8 { get { return value8; } set { value8 = value; } }
        public String VALUE9 { get { return value9; } set { value9 = value; } }
        public String VALUE10 { get { return value10; } set { value10 = value; } }
        public String VALUE11 { get { return value11; } set { value11 = value; } }
        public String VALUE12 { get { return value12; } set { value12 = value; } }
        public String VALUE13 { get { return value13; } set { value13 = value; } }
        public String VALUE14 { get { return value14; } set { value14 = value; } }
        public String VALUE15 { get { return value15; } set { value15 = value; } }
        public String VALUE16 { get { return value16; } set { value16 = value; } }
        public String VALUE17 { get { return value17; } set { value17 = value; } }
        public String VALUE18 { get { return value18; } set { value18 = value; } }
        public String VALUE19 { get { return value19; } set { value19 = value; } }
        public String VALUE20 { get { return value20; } set { value20 = value; } }
        public String VALUE21 { get { return value21; } set { value21 = value; } }
        public String VALUE22 { get { return value22; } set { value22 = value; } }
        public String VALUE23 { get { return value23; } set { value23 = value; } }
        public String VALUE24 { get { return value24; } set { value24 = value; } }
        public String VALUE25 { get { return value25; } set { value25 = value; } }
        public String VALUE26 { get { return value26; } set { value26 = value; } }
        public String VALUE27 { get { return value27; } set { value27 = value; } }
        public String VALUE28 { get { return value28; } set { value28 = value; } }
        public String VALUE29 { get { return value29; } set { value29 = value; } }
        public String VALUE30 { get { return value30; } set { value30 = value; } }
        public String VALUE31 { get { return value31; } set { value31 = value; } }
        public String VALUE32 { get { return value32; } set { value32 = value; } }
        public String VALUE33 { get { return value33; } set { value33 = value; } }
        public String VALUE34 { get { return value34; } set { value34 = value; } }
        public String VALUE35 { get { return value35; } set { value35 = value; } }
        public String VALUE36 { get { return value36; } set { value36 = value; } }
        public String VALUE37 { get { return value37; } set { value37 = value; } }
        public String VALUE38 { get { return value38; } set { value38 = value; } }
        public String VALUE39 { get { return value39; } set { value39 = value; } }
        public String VALUE40 { get { return value40; } set { value40 = value; } }
        public String VALUE41 { get { return value41; } set { value41 = value; } }
        public String VALUE42 { get { return value42; } set { value42 = value; } }
        public String VALUE43 { get { return value43; } set { value43 = value; } }
        public String VALUE44 { get { return value44; } set { value44 = value; } }
        public String VALUE45 { get { return value45; } set { value45 = value; } }
        public String VALUE46 { get { return value46; } set { value46 = value; } }
        public String VALUE47 { get { return value47; } set { value47 = value; } }
        public String VALUE48 { get { return value48; } set { value48 = value; } }
        public String VALUE49 { get { return value49; } set { value49 = value; } }
        public String VALUE50 { get { return value50; } set { value50 = value; } }
        public String VALUE51 { get { return value51; } set { value51 = value; } }
        public String VALUE52 { get { return value52; } set { value52 = value; } }
        public String VALUE53 { get { return value53; } set { value53 = value; } }
        public String VALUE54 { get { return value54; } set { value54 = value; } }
        public String VALUE55 { get { return value55; } set { value55 = value; } }
        public String VALUE56 { get { return value56; } set { value56 = value; } }
        public String VALUE57 { get { return value57; } set { value57 = value; } }
        public String VALUE58 { get { return value58; } set { value58 = value; } }
        public String VALUE59 { get { return value59; } set { value59 = value; } }
        public String VALUE60 { get { return value60; } set { value60 = value; } }
        public String VALUE61 { get { return value61; } set { value61 = value; } }
        public String VALUE62 { get { return value62; } set { value62 = value; } }
        public String VALUE63 { get { return value63; } set { value63 = value; } }
        public String VALUE64 { get { return value64; } set { value64 = value; } }
        public String VALUE65 { get { return value65; } set { value65 = value; } }
        public String VALUE66 { get { return value66; } set { value66 = value; } }
        public String VALUE67 { get { return value67; } set { value67 = value; } }
        public String VALUE68 { get { return value68; } set { value68 = value; } }
        public String VALUE69 { get { return value69; } set { value69 = value; } }
        public String VALUE70 { get { return value70; } set { value70 = value; } }
        public String VALUE71 { get { return value71; } set { value71 = value; } }
        public String VALUE72 { get { return value72; } set { value72 = value; } }
        public String VALUE73 { get { return value73; } set { value73 = value; } }
        public String VALUE74 { get { return value74; } set { value74 = value; } }
        public String VALUE75 { get { return value75; } set { value75 = value; } }
        public String VALUE76 { get { return value76; } set { value76 = value; } }
        public String VALUE77 { get { return value77; } set { value77 = value; } }
        public String VALUE78 { get { return value78; } set { value78 = value; } }
        public String VALUE79 { get { return value79; } set { value79 = value; } }
        public String VALUE80 { get { return value80; } set { value80 = value; } }
        public String VALUE81 { get { return value81; } set { value81 = value; } }
        public String VALUE82 { get { return value82; } set { value82 = value; } }
        public String VALUE83 { get { return value83; } set { value83 = value; } }
        public String VALUE84 { get { return value84; } set { value84 = value; } }
        public String VALUE85 { get { return value85; } set { value85 = value; } }
        public String VALUE86 { get { return value86; } set { value86 = value; } }
        public String VALUE87 { get { return value87; } set { value87 = value; } }
        public String VALUE88 { get { return value88; } set { value88 = value; } }
        public String VALUE89 { get { return value89; } set { value89 = value; } }
        public String VALUE90 { get { return value90; } set { value90 = value; } }
        public String VALUE91 { get { return value91; } set { value91 = value; } }
        public String VALUE92 { get { return value92; } set { value92 = value; } }
        public String VALUE93 { get { return value93; } set { value93 = value; } }
        public String VALUE94 { get { return value94; } set { value94 = value; } }
        public String VALUE95 { get { return value95; } set { value95 = value; } }
        public String VALUE96 { get { return value96; } set { value96 = value; } }
        public String VALUE97 { get { return value97; } set { value97 = value; } }
        public String VALUE98 { get { return value98; } set { value98 = value; } }
        public String VALUE99 { get { return value99; } set { value99 = value; } }
        public String VALUE100 { get { return value100; } set { value100 = value; } }

        //public int iVALUE1 { get { return ivalue1; } set { ivalue1 = value; } }
        //public int iVALUE2 { get { return ivalue2; } set { ivalue2 = value; } }
        //public int iVALUE3 { get { return ivalue3; } set { ivalue3 = value; } }
        //public int iVALUE4 { get { return ivalue4; } set { ivalue4 = value; } }
        //public int iVALUE5 { get { return ivalue5; } set { ivalue5 = value; } }
        //public int iVALUE6 { get { return ivalue6; } set { ivalue6 = value; } }
        //public int iVALUE7 { get { return ivalue7; } set { ivalue7 = value; } }
        //public int iVALUE8 { get { return ivalue8; } set { ivalue8 = value; } }
        //public int iVALUE9 { get { return ivalue9; } set { ivalue9 = value; } }
        //public int iVALUE10 { get { return ivalue10; } set { ivalue10 = value; } }
        //public int iVALUE11 { get { return ivalue11; } set { ivalue11 = value; } }
        //public int iVALUE12 { get { return ivalue12; } set { ivalue12 = value; } }
        //public int iVALUE13 { get { return ivalue13; } set { ivalue13 = value; } }
        //public int iVALUE14 { get { return ivalue14; } set { ivalue14 = value; } }
        //public int iVALUE15 { get { return ivalue15; } set { ivalue15 = value; } }
        //public int iVALUE16 { get { return ivalue16; } set { ivalue16 = value; } }
        //public int iVALUE17 { get { return ivalue17; } set { ivalue17 = value; } }
        //public int iVALUE18 { get { return ivalue18; } set { ivalue18 = value; } }
        //public int iVALUE19 { get { return ivalue19; } set { ivalue19 = value; } }
        //public int iVALUE20 { get { return ivalue20; } set { ivalue20 = value; } }
        //public int iVALUE21 { get { return ivalue21; } set { ivalue21 = value; } }
        //public int iVALUE22 { get { return ivalue22; } set { ivalue22 = value; } }
        //public int iVALUE23 { get { return ivalue23; } set { ivalue23 = value; } }
        //public int iVALUE24 { get { return ivalue24; } set { ivalue24 = value; } }
        //public int iVALUE25 { get { return ivalue25; } set { ivalue25 = value; } }
        //public int iVALUE26 { get { return ivalue26; } set { ivalue26 = value; } }
        //public int iVALUE27 { get { return ivalue27; } set { ivalue27 = value; } }
        //public int iVALUE28 { get { return ivalue28; } set { ivalue28 = value; } }
        //public int iVALUE29 { get { return ivalue29; } set { ivalue29 = value; } }
        //public int iVALUE30 { get { return ivalue30; } set { ivalue30 = value; } }
        //public int iVALUE31 { get { return ivalue31; } set { ivalue31 = value; } }
        //public int iVALUE32 { get { return ivalue32; } set { ivalue32 = value; } }
        //public int iVALUE33 { get { return ivalue33; } set { ivalue33 = value; } }
        //public int iVALUE34 { get { return ivalue34; } set { ivalue34 = value; } }
        //public int iVALUE35 { get { return ivalue35; } set { ivalue35 = value; } }
        //public int iVALUE36 { get { return ivalue36; } set { ivalue36 = value; } }
        //public int iVALUE37 { get { return ivalue37; } set { ivalue37 = value; } }
        //public int iVALUE38 { get { return ivalue38; } set { ivalue38 = value; } }
        //public int iVALUE39 { get { return ivalue39; } set { ivalue39 = value; } }
        //public int iVALUE40 { get { return ivalue40; } set { ivalue40 = value; } }
        //public int iVALUE41 { get { return ivalue41; } set { ivalue41 = value; } }
        //public int iVALUE42 { get { return ivalue42; } set { ivalue42 = value; } }
        //public int iVALUE43 { get { return ivalue43; } set { ivalue43 = value; } }
        //public int iVALUE44 { get { return ivalue44; } set { ivalue44 = value; } }
        //public int iVALUE45 { get { return ivalue45; } set { ivalue45 = value; } }
        //public int iVALUE46 { get { return ivalue46; } set { ivalue46 = value; } }
        //public int iVALUE47 { get { return ivalue47; } set { ivalue47 = value; } }
        //public int iVALUE48 { get { return ivalue48; } set { ivalue48 = value; } }
        //public int iVALUE49 { get { return ivalue49; } set { ivalue49 = value; } }
        //public int iVALUE50 { get { return ivalue50; } set { ivalue50 = value; } }
        //public int iVALUE51 { get { return ivalue51; } set { ivalue51 = value; } }
        //public int iVALUE52 { get { return ivalue52; } set { ivalue52 = value; } }
        //public int iVALUE53 { get { return ivalue53; } set { ivalue53 = value; } }
        //public int iVALUE54 { get { return ivalue54; } set { ivalue54 = value; } }
        //public int iVALUE55 { get { return ivalue55; } set { ivalue55 = value; } }
        //public int iVALUE56 { get { return ivalue56; } set { ivalue56 = value; } }
        //public int iVALUE57 { get { return ivalue57; } set { ivalue57 = value; } }
        //public int iVALUE58 { get { return ivalue58; } set { ivalue58 = value; } }
        //public int iVALUE59 { get { return ivalue59; } set { ivalue59 = value; } }
        //public int iVALUE60 { get { return ivalue60; } set { ivalue60 = value; } }
        //public int iVALUE61 { get { return ivalue61; } set { ivalue61 = value; } }
        //public int iVALUE62 { get { return ivalue62; } set { ivalue62 = value; } }
        //public int iVALUE63 { get { return ivalue63; } set { ivalue63 = value; } }
        //public int iVALUE64 { get { return ivalue64; } set { ivalue64 = value; } }
        //public int iVALUE65 { get { return ivalue65; } set { ivalue65 = value; } }
        //public int iVALUE66 { get { return ivalue66; } set { ivalue66 = value; } }
        //public int iVALUE67 { get { return ivalue67; } set { ivalue67 = value; } }
        //public int iVALUE68 { get { return ivalue68; } set { ivalue68 = value; } }
        //public int iVALUE69 { get { return ivalue69; } set { ivalue69 = value; } }
        //public int iVALUE70 { get { return ivalue70; } set { ivalue70 = value; } }
        //public int iVALUE71 { get { return ivalue71; } set { ivalue71 = value; } }
        //public int iVALUE72 { get { return ivalue72; } set { ivalue72 = value; } }
        //public int iVALUE73 { get { return ivalue73; } set { ivalue73 = value; } }
        //public int iVALUE74 { get { return ivalue74; } set { ivalue74 = value; } }
        //public int iVALUE75 { get { return ivalue75; } set { ivalue75 = value; } }
        //public int iVALUE76 { get { return ivalue76; } set { ivalue76 = value; } }
        //public int iVALUE77 { get { return ivalue77; } set { ivalue77 = value; } }
        //public int iVALUE78 { get { return ivalue78; } set { ivalue78 = value; } }
        //public int iVALUE79 { get { return ivalue79; } set { ivalue79 = value; } }
        //public int iVALUE70 { get { return ivalue70; } set { ivalue70 = value; } }
        //public int iVALUE81 { get { return ivalue81; } set { ivalue81 = value; } }
        //public int iVALUE82 { get { return ivalue82; } set { ivalue82 = value; } }
        //public int iVALUE83 { get { return ivalue83; } set { ivalue83 = value; } }
        //public int iVALUE84 { get { return ivalue84; } set { ivalue84 = value; } }
        //public int iVALUE85 { get { return ivalue85; } set { ivalue85 = value; } }
        //public int iVALUE86 { get { return ivalue86; } set { ivalue86 = value; } }
        //public int iVALUE87 { get { return ivalue87; } set { ivalue87 = value; } }
        //public int iVALUE88 { get { return ivalue88; } set { ivalue88 = value; } }
        //public int iVALUE89 { get { return ivalue89; } set { ivalue89 = value; } }
        //public int iVALUE90 { get { return ivalue90; } set { ivalue90 = value; } }
        //public int iVALUE91 { get { return ivalue91; } set { ivalue91 = value; } }
        //public int iVALUE92 { get { return ivalue92; } set { ivalue92 = value; } }
        //public int iVALUE93 { get { return ivalue93; } set { ivalue93 = value; } }
        //public int iVALUE94 { get { return ivalue94; } set { ivalue94 = value; } }
        //public int iVALUE95 { get { return ivalue95; } set { ivalue95 = value; } }
        //public int iVALUE96 { get { return ivalue96; } set { ivalue96 = value; } }
        //public int iVALUE97 { get { return ivalue97; } set { ivalue97 = value; } }
        //public int iVALUE98 { get { return ivalue98; } set { ivalue98 = value; } }
        //public int iVALUE99 { get { return ivalue99; } set { ivalue99 = value; } }
        //public int iVALUE100 { get { return ivalue100; } set { ivalue100 = value; } }

        public CrystalReportField(ArrayList pValue)
        {
            if (pValue.Count > 0) { value1 = pValue[0].ToString(); }
            if (pValue.Count > 1) { value2 = pValue[1].ToString(); }
            if (pValue.Count > 2) { value3 = pValue[2].ToString(); }
            if (pValue.Count > 3) { value4 = pValue[3].ToString(); }
            if (pValue.Count > 4) { value5 = pValue[4].ToString(); }
            if (pValue.Count > 5) { value6 = pValue[5].ToString(); }
            if (pValue.Count > 6) { value7 = pValue[6].ToString(); }
            if (pValue.Count > 7) { value8 = pValue[7].ToString(); }
            if (pValue.Count > 8) { value9 = pValue[8].ToString(); }
            if (pValue.Count > 9) { value10 = pValue[9].ToString(); }
            if (pValue.Count > 10) { value11 = pValue[10].ToString(); }
            if (pValue.Count > 11) { value12 = pValue[11].ToString(); }
            if (pValue.Count > 12) { value13 = pValue[12].ToString(); }
            if (pValue.Count > 13) { value14 = pValue[13].ToString(); }
            if (pValue.Count > 14) { value15 = pValue[14].ToString(); }
            if (pValue.Count > 15) { value16 = pValue[15].ToString(); }
            if (pValue.Count > 16) { value17 = pValue[16].ToString(); }
            if (pValue.Count > 17) { value18 = pValue[17].ToString(); }
            if (pValue.Count > 18) { value19 = pValue[18].ToString(); }
            if (pValue.Count > 19) { value20 = pValue[19].ToString(); }
            if (pValue.Count > 20) { value21 = pValue[20].ToString(); }
            if (pValue.Count > 21) { value22 = pValue[21].ToString(); }
            if (pValue.Count > 22) { value23 = pValue[22].ToString(); }
            if (pValue.Count > 23) { value24 = pValue[23].ToString(); }
            if (pValue.Count > 24) { value25 = pValue[24].ToString(); }
            if (pValue.Count > 25) { value26 = pValue[25].ToString(); }
            if (pValue.Count > 26) { value27 = pValue[26].ToString(); }
            if (pValue.Count > 27) { value28 = pValue[27].ToString(); }
            if (pValue.Count > 28) { value29 = pValue[28].ToString(); }
            if (pValue.Count > 29) { value30 = pValue[29].ToString(); }
            if (pValue.Count > 30) { value31 = pValue[30].ToString(); }
            if (pValue.Count > 31) { value32 = pValue[31].ToString(); }
            if (pValue.Count > 32) { value33 = pValue[32].ToString(); }
            if (pValue.Count > 33) { value34 = pValue[33].ToString(); }
            if (pValue.Count > 34) { value35 = pValue[34].ToString(); }
            if (pValue.Count > 35) { value36 = pValue[35].ToString(); }
            if (pValue.Count > 36) { value37 = pValue[36].ToString(); }
            if (pValue.Count > 37) { value38 = pValue[37].ToString(); }
            if (pValue.Count > 38) { value39 = pValue[38].ToString(); }
            if (pValue.Count > 39) { value40 = pValue[39].ToString(); }
            if (pValue.Count > 40) { value41 = pValue[40].ToString(); }
            if (pValue.Count > 41) { value42 = pValue[41].ToString(); }
            if (pValue.Count > 42) { value43 = pValue[42].ToString(); }
            if (pValue.Count > 43) { value44 = pValue[43].ToString(); }
            if (pValue.Count > 44) { value45 = pValue[44].ToString(); }
            if (pValue.Count > 45) { value46 = pValue[45].ToString(); }
            if (pValue.Count > 46) { value47 = pValue[46].ToString(); }
            if (pValue.Count > 47) { value48 = pValue[47].ToString(); }
            if (pValue.Count > 48) { value49 = pValue[48].ToString(); }
            if (pValue.Count > 49) { value50 = pValue[49].ToString(); }
            if (pValue.Count > 50) { value51 = pValue[50].ToString(); }
            if (pValue.Count > 51) { value52 = pValue[51].ToString(); }
            if (pValue.Count > 52) { value53 = pValue[52].ToString(); }
            if (pValue.Count > 53) { value54 = pValue[53].ToString(); }
            if (pValue.Count > 54) { value55 = pValue[54].ToString(); }
            if (pValue.Count > 55) { value56 = pValue[55].ToString(); }
            if (pValue.Count > 56) { value57 = pValue[56].ToString(); }
            if (pValue.Count > 57) { value58 = pValue[57].ToString(); }
            if (pValue.Count > 58) { value59 = pValue[58].ToString(); }
            if (pValue.Count > 59) { value60 = pValue[59].ToString(); }
            if (pValue.Count > 60) { value61 = pValue[60].ToString(); }
            if (pValue.Count > 61) { value62 = pValue[61].ToString(); }
            if (pValue.Count > 62) { value63 = pValue[62].ToString(); }
            if (pValue.Count > 63) { value64 = pValue[63].ToString(); }
            if (pValue.Count > 64) { value65 = pValue[64].ToString(); }
            if (pValue.Count > 65) { value66 = pValue[65].ToString(); }
            if (pValue.Count > 66) { value67 = pValue[66].ToString(); }
            if (pValue.Count > 67) { value68 = pValue[67].ToString(); }
            if (pValue.Count > 68) { value69 = pValue[68].ToString(); }
            if (pValue.Count > 69) { value70 = pValue[69].ToString(); }
            if (pValue.Count > 70) { value71 = pValue[70].ToString(); }
            if (pValue.Count > 71) { value72 = pValue[71].ToString(); }
            if (pValue.Count > 72) { value73 = pValue[72].ToString(); }
            if (pValue.Count > 73) { value74 = pValue[73].ToString(); }
            if (pValue.Count > 74) { value75 = pValue[74].ToString(); }
            if (pValue.Count > 75) { value76 = pValue[75].ToString(); }
            if (pValue.Count > 76) { value77 = pValue[76].ToString(); }
            if (pValue.Count > 77) { value78 = pValue[77].ToString(); }
            if (pValue.Count > 78) { value79 = pValue[78].ToString(); }
            if (pValue.Count > 79) { value70 = pValue[79].ToString(); }
            if (pValue.Count > 70) { value81 = pValue[70].ToString(); }
            if (pValue.Count > 81) { value82 = pValue[81].ToString(); }
            if (pValue.Count > 82) { value83 = pValue[82].ToString(); }
            if (pValue.Count > 83) { value84 = pValue[83].ToString(); }
            if (pValue.Count > 84) { value85 = pValue[84].ToString(); }
            if (pValue.Count > 85) { value86 = pValue[85].ToString(); }
            if (pValue.Count > 86) { value87 = pValue[86].ToString(); }
            if (pValue.Count > 87) { value88 = pValue[87].ToString(); }
            if (pValue.Count > 88) { value89 = pValue[88].ToString(); }
            if (pValue.Count > 89) { value90 = pValue[89].ToString(); }
            if (pValue.Count > 90) { value91 = pValue[90].ToString(); }
            if (pValue.Count > 91) { value92 = pValue[91].ToString(); }
            if (pValue.Count > 92) { value93 = pValue[92].ToString(); }
            if (pValue.Count > 93) { value94 = pValue[93].ToString(); }
            if (pValue.Count > 94) { value95 = pValue[94].ToString(); }
            if (pValue.Count > 95) { value96 = pValue[95].ToString(); }
            if (pValue.Count > 96) { value97 = pValue[96].ToString(); }
            if (pValue.Count > 97) { value98 = pValue[97].ToString(); }
            if (pValue.Count > 98) { value99 = pValue[98].ToString(); }
            if (pValue.Count > 99) { value100 = pValue[99].ToString(); }
        }
    }
}
